name: Hello world Docker
on:
  push:
    branches: [ main ]
    paths-ignore: [ .github/** ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      receiver:
        description: 'Who should we greet?'
        required: true
        default: ${{ github.actor }}

jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0

    - name: Container time
      id: hello-action
      uses: ./actions/hello-world-docker-action
      with:
        who-to-greet: ${{ inputs.receiver }}

    - name: Output time
      run: echo "${{ steps.hello-action.outputs.time }}"