name: Hello world Docker
on:
  push:
    branches: [ main ]
    paths-ignore: [ .github/** ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0

    - name: Container time
      id: hello-action
      uses: ./actions/hello-world-docker-action
      with:
        who-to-greet: 'Me'

    - name: Output time
      run: echo "${{ steps.hello-action.outputs.time }}"