name: Hello world Docker
on:
  push:
    branches: [ main ]
    paths-ignore: [ .github/** ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Hello:
    uses: actions/hello-world-docker-action@main
    with:
      who-to-greet: 'Me'
