name: Reuse other workflow

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}'
  call-workflow:
    needs: [debug]
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: '${{ github.triggering_actor }}'
  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - run: echo "Time during workflow ${{ needs.call-workflow.outputs.current-time }}"